// <auto-generated />
using System;
using MediMateRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediMateRepository.Migrations
{
    [DbContext(typeof(MediMateDbContext))]
    [Migration("20260209164414_addPrescription")]
    partial class addPrescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediMateRepository.Model.Families", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<string>("JoinCode")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("FamilyId");

                    b.HasIndex("CreateBy");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthConditions", b =>
                {
                    b.Property<Guid>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiagnosedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConditionId");

                    b.HasIndex("HealthProfileId");

                    b.ToTable("HealthConditions");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthProfiles", b =>
                {
                    b.Property<Guid>("HealthProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("HealthProfileId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("HealthProfiles");
                });

            modelBuilder.Entity("MediMateRepository.Model.Members", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncTokenExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MemberId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionImages", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("OcrRawData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ImageId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionImages");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionMedicines", b =>
                {
                    b.Property<Guid>("PrescriptionMedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiParsedInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PrescriptionMedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionMedicines");
                });

            modelBuilder.Entity("MediMateRepository.Model.Prescriptions", b =>
                {
                    b.Property<Guid>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("MemberId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MediMateRepository.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiriedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int?>("VerifyCode")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MediMateRepository.Model.Families", b =>
                {
                    b.HasOne("MediMateRepository.Model.User", "Creator")
                        .WithMany("CreatedFamilies")
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthConditions", b =>
                {
                    b.HasOne("MediMateRepository.Model.HealthProfiles", "HealthProfile")
                        .WithMany("Conditions")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthProfiles", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithOne("HealthProfile")
                        .HasForeignKey("MediMateRepository.Model.HealthProfiles", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.Members", b =>
                {
                    b.HasOne("MediMateRepository.Model.Families", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediMateRepository.Model.User", null)
                        .WithMany("MemberProfiles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionImages", b =>
                {
                    b.HasOne("MediMateRepository.Model.Prescriptions", "Prescription")
                        .WithMany("PrescriptionImages")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionMedicines", b =>
                {
                    b.HasOne("MediMateRepository.Model.Prescriptions", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediMateRepository.Model.Prescriptions", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.Families", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthProfiles", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("MediMateRepository.Model.Members", b =>
                {
                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("MediMateRepository.Model.Prescriptions", b =>
                {
                    b.Navigation("PrescriptionImages");

                    b.Navigation("PrescriptionMedicines");
                });

            modelBuilder.Entity("MediMateRepository.Model.User", b =>
                {
                    b.Navigation("CreatedFamilies");

                    b.Navigation("MemberProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
