// <auto-generated />
using System;
using MediMateRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediMateRepository.Migrations
{
    [DbContext(typeof(MediMateDbContext))]
    partial class MediMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediMateRepository.Model.ActivityLogs", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("MediMateRepository.Model.Appointments", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MemberId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatDoctorMessages", b =>
                {
                    b.Property<Guid>("ChatDoctorMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ConsultanSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ChatDoctorMessageId");

                    b.HasIndex("ConsultanSessionId");

                    b.ToTable("ChatDoctorMessages");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatbotMessages", b =>
                {
                    b.Property<Guid>("BotMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("BotMessageId");

                    b.HasIndex("BotSessionId");

                    b.ToTable("ChatbotMessages");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatbotSession", b =>
                {
                    b.Property<Guid>("BotSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BotSessionId");

                    b.HasIndex("MemberId");

                    b.ToTable("ChatbotSessions");
                });

            modelBuilder.Entity("MediMateRepository.Model.ConsultationSessions", b =>
                {
                    b.Property<Guid>("ConsultanSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DoctorJoined")
                        .HasColumnType("boolean");

                    b.Property<string>("DoctorNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GuardianJoined")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GuardianUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("RecordUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UserJoined")
                        .HasColumnType("boolean");

                    b.HasKey("ConsultanSessionId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("GuardianUserId");

                    b.HasIndex("MemberId");

                    b.ToTable("ConsultationSessions");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorAvailability", b =>
                {
                    b.Property<Guid>("DoctorAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("DoctorAvailabilityId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorAvailabilityExceptions", b =>
                {
                    b.Property<Guid>("ExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvailableOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("ExceptionId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilityExceptions");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorBankAccount", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.HasKey("BankAccountId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorBankAccounts");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ReviewAt")
                        .HasColumnType("text");

                    b.Property<string>("ReviewBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DocumentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorDocuments");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorPayout", b =>
                {
                    b.Property<Guid>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PayoutId");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("RateId");

                    b.ToTable("DoctorPayouts");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorPayoutRate", b =>
                {
                    b.Property<Guid>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPerSession")
                        .HasColumnType("numeric");

                    b.Property<string>("ConsultationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("RateId");

                    b.ToTable("DoctorPayoutRates");
                });

            modelBuilder.Entity("MediMateRepository.Model.Doctors", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentHospitalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LicenseImage")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("MediMateRepository.Model.Families", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FamilyAvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<bool>("IsOpenJoin")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("NotificationSettingSettingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("FamilyId");

                    b.HasIndex("CreateBy");

                    b.HasIndex("NotificationSettingSettingId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("MediMateRepository.Model.FamilySubscriptions", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int>("RemainingConsultantCount")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingOcrCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("FamilySubscriptions");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthConditions", b =>
                {
                    b.Property<Guid>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiagnosedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConditionId");

                    b.HasIndex("HealthProfileId");

                    b.ToTable("HealthConditions");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthProfiles", b =>
                {
                    b.Property<Guid>("HealthProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("HealthProfileId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("HealthProfiles");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationLogs", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ReminderId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("MedicationLogs");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationReminders", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcknowledgedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReminderId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("MedicationReminders");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationScheduleDetails", b =>
                {
                    b.Property<Guid>("ScheduleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PrescriptionMedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ScheduleDetailId");

                    b.HasIndex("PrescriptionMedicineId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("MedicationScheduleDetails");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationSchedules", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TimeOfDay")
                        .HasColumnType("interval");

                    b.HasKey("ScheduleId");

                    b.HasIndex("MemberId");

                    b.ToTable("MedicationSchedules");
                });

            modelBuilder.Entity("MediMateRepository.Model.Members", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FamilyId1")
                        .HasColumnType("uuid");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NotificationSettingSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncTokenExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MemberId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FamilyId1");

                    b.HasIndex("NotificationSettingSettingId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MediMateRepository.Model.MembershipPackages", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsultantLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberLimit")
                        .HasColumnType("integer");

                    b.Property<int>("OcrLimit")
                        .HasColumnType("integer");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("PackageId");

                    b.ToTable("MembershipPackages");
                });

            modelBuilder.Entity("MediMateRepository.Model.NotificationSetting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomSetting")
                        .HasColumnType("text");

                    b.Property<bool>("EnableEmailNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableFamilyAlert")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnablePushNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableSmsNotification")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxDosesPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumHoursGap")
                        .HasColumnType("integer");

                    b.Property<int>("MissedDosesThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("ReminderAdvanceMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SettingId");

                    b.HasIndex("FamilyId")
                        .IsUnique();

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("MediMateRepository.Model.Notifications", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MediMateRepository.Model.Payments", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentContent")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionImages", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("OcrRawData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ImageId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionImages");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionMedicines", b =>
                {
                    b.Property<Guid>("PrescriptionMedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiParsedInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PrescriptionMedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionMedicines");
                });

            modelBuilder.Entity("MediMateRepository.Model.Prescriptions", b =>
                {
                    b.Property<Guid>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("MemberId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionsByDoctor", b =>
                {
                    b.Property<Guid>("DigitalPrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advice")
                        .HasColumnType("text");

                    b.Property<Guid>("ConsultanSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicinesList")
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("DigitalPrescriptionId");

                    b.HasIndex("ConsultanSessionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MemberId");

                    b.ToTable("PrescriptionsByDoctor");
                });

            modelBuilder.Entity("MediMateRepository.Model.RagBaseCollection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CollectionId");

                    b.ToTable("RagBaseCollections");
                });

            modelBuilder.Entity("MediMateRepository.Model.RagBaseConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUseApi")
                        .HasColumnType("boolean");

                    b.Property<string>("LLMModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int>("TopK")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ConfigId");

                    b.ToTable("RagBaseConfigs");
                });

            modelBuilder.Entity("MediMateRepository.Model.RagBaseDocument", b =>
                {
                    b.Property<Guid>("RagDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RagDocumentId");

                    b.HasIndex("CollectionId");

                    b.ToTable("RagBaseDocuments");
                });

            modelBuilder.Entity("MediMateRepository.Model.RagBaseEmbedding", b =>
                {
                    b.Property<Guid>("EmbeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.PrimitiveCollection<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RagDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmbeddingId");

                    b.HasIndex("RagDocumentId");

                    b.ToTable("RagBaseEmbeddings");
                });

            modelBuilder.Entity("MediMateRepository.Model.Ratings", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConsultanSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsultationSessionsConsultanSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("RatingId");

                    b.HasIndex("ConsultanSessionId");

                    b.HasIndex("ConsultationSessionsConsultanSessionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MemberId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MediMateRepository.Model.Transactions", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<string>("GatewayName")
                        .HasColumnType("text");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<string>("GatewayTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PayoutId");

                    b.HasIndex("TransactionCode")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MediMateRepository.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiriedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int?>("VerifyCode")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MediMateRepository.Model.ActivityLogs", b =>
                {
                    b.HasOne("MediMateRepository.Model.Families", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.Appointments", b =>
                {
                    b.HasOne("MediMateRepository.Model.DoctorAvailability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Doctor");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatDoctorMessages", b =>
                {
                    b.HasOne("MediMateRepository.Model.ConsultationSessions", "ConsultantSession")
                        .WithMany("Messages")
                        .HasForeignKey("ConsultanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultantSession");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatbotMessages", b =>
                {
                    b.HasOne("MediMateRepository.Model.ChatbotSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("BotSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatbotSession", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.ConsultationSessions", b =>
                {
                    b.HasOne("MediMateRepository.Model.Appointments", "Appointment")
                        .WithOne()
                        .HasForeignKey("MediMateRepository.Model.ConsultationSessions", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.User", "Guardian")
                        .WithMany()
                        .HasForeignKey("GuardianUserId");

                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Guardian");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorAvailability", b =>
                {
                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorAvailabilityExceptions", b =>
                {
                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorBankAccount", b =>
                {
                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorDocument", b =>
                {
                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany("DoctorDocuments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediMateRepository.Model.DoctorPayout", b =>
                {
                    b.HasOne("MediMateRepository.Model.ConsultationSessions", "ConsultationSession")
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.DoctorPayoutRate", "Rate")
                        .WithMany()
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultationSession");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("MediMateRepository.Model.Doctors", b =>
                {
                    b.HasOne("MediMateRepository.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediMateRepository.Model.Families", b =>
                {
                    b.HasOne("MediMateRepository.Model.User", "Creator")
                        .WithMany("CreatedFamilies")
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.NotificationSetting", "NotificationSetting")
                        .WithMany()
                        .HasForeignKey("NotificationSettingSettingId");

                    b.Navigation("Creator");

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("MediMateRepository.Model.FamilySubscriptions", b =>
                {
                    b.HasOne("MediMateRepository.Model.Families", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.MembershipPackages", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthConditions", b =>
                {
                    b.HasOne("MediMateRepository.Model.HealthProfiles", "HealthProfile")
                        .WithMany("Conditions")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthProfiles", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithOne("HealthProfile")
                        .HasForeignKey("MediMateRepository.Model.HealthProfiles", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationLogs", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.MedicationReminders", "Reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.MedicationSchedules", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Reminder");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationReminders", b =>
                {
                    b.HasOne("MediMateRepository.Model.MedicationSchedules", "Schedule")
                        .WithMany("MedicationReminders")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationScheduleDetails", b =>
                {
                    b.HasOne("MediMateRepository.Model.PrescriptionMedicines", "PrescriptionMedicine")
                        .WithMany()
                        .HasForeignKey("PrescriptionMedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.MedicationSchedules", "Schedule")
                        .WithMany("ScheduleDetails")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrescriptionMedicine");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationSchedules", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.Members", b =>
                {
                    b.HasOne("MediMateRepository.Model.Families", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediMateRepository.Model.Families", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId1");

                    b.HasOne("MediMateRepository.Model.NotificationSetting", "NotificationSetting")
                        .WithMany()
                        .HasForeignKey("NotificationSettingSettingId");

                    b.HasOne("MediMateRepository.Model.User", null)
                        .WithMany("MemberProfiles")
                        .HasForeignKey("UserId");

                    b.Navigation("Family");

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("MediMateRepository.Model.NotificationSetting", b =>
                {
                    b.HasOne("MediMateRepository.Model.Families", "Family")
                        .WithOne()
                        .HasForeignKey("MediMateRepository.Model.NotificationSetting", "FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("MediMateRepository.Model.Notifications", b =>
                {
                    b.HasOne("MediMateRepository.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediMateRepository.Model.Payments", b =>
                {
                    b.HasOne("MediMateRepository.Model.FamilySubscriptions", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionImages", b =>
                {
                    b.HasOne("MediMateRepository.Model.Prescriptions", "Prescription")
                        .WithMany("PrescriptionImages")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionMedicines", b =>
                {
                    b.HasOne("MediMateRepository.Model.Prescriptions", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediMateRepository.Model.Prescriptions", b =>
                {
                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.PrescriptionsByDoctor", b =>
                {
                    b.HasOne("MediMateRepository.Model.ConsultationSessions", "Session")
                        .WithMany()
                        .HasForeignKey("ConsultanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MediMateRepository.Model.RagBaseDocument", b =>
                {
                    b.HasOne("MediMateRepository.Model.RagBaseCollection", "RagBaseCollection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RagBaseCollection");
                });

            modelBuilder.Entity("MediMateRepository.Model.RagBaseEmbedding", b =>
                {
                    b.HasOne("MediMateRepository.Model.RagBaseDocument", "RagBaseDocument")
                        .WithMany()
                        .HasForeignKey("RagDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RagBaseDocument");
                });

            modelBuilder.Entity("MediMateRepository.Model.Ratings", b =>
                {
                    b.HasOne("MediMateRepository.Model.ConsultationSessions", "ConsultationSession")
                        .WithMany()
                        .HasForeignKey("ConsultanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.ConsultationSessions", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ConsultationSessionsConsultanSessionId");

                    b.HasOne("MediMateRepository.Model.Doctors", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MediMateRepository.Model.Members", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConsultationSession");

                    b.Navigation("Doctor");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediMateRepository.Model.Transactions", b =>
                {
                    b.HasOne("MediMateRepository.Model.Payments", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediMateRepository.Model.DoctorPayout", "Payout")
                        .WithMany()
                        .HasForeignKey("PayoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");

                    b.Navigation("Payout");
                });

            modelBuilder.Entity("MediMateRepository.Model.ChatbotSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MediMateRepository.Model.ConsultationSessions", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MediMateRepository.Model.Doctors", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("DoctorDocuments");
                });

            modelBuilder.Entity("MediMateRepository.Model.Families", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("MediMateRepository.Model.HealthProfiles", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("MediMateRepository.Model.MedicationSchedules", b =>
                {
                    b.Navigation("MedicationReminders");

                    b.Navigation("ScheduleDetails");
                });

            modelBuilder.Entity("MediMateRepository.Model.Members", b =>
                {
                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("MediMateRepository.Model.Payments", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MediMateRepository.Model.Prescriptions", b =>
                {
                    b.Navigation("PrescriptionImages");

                    b.Navigation("PrescriptionMedicines");
                });

            modelBuilder.Entity("MediMateRepository.Model.User", b =>
                {
                    b.Navigation("CreatedFamilies");

                    b.Navigation("MemberProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
